services:
  web:
    image: nginx
    volumes: 
      - /home/ubuntu/docker/nginx:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGNIX_HOST=simplyshare.xyz
      - NGINX_PORT=80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=http"
      - "traefik.http.routers.nginx.rule-Host('simplyshare.xyz')"
      - "traefik.http.middlewares.nginx-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nginx.middlewares-jellyfin-https-redirect" 
      - "traefik.http.routers.nginx-secure.entrypoints=https"
      - "traefik.http.routers.nginx-secure.rule-Host(simplyshare.xyz)"
      - "traefik.http.routers.nginx-secure.tls-true" 
      - "traefik.http.routers.nginx-secure.service-nginx" 
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      - "traefik.docker.network-proxy"
    networks:
      - proxy
    # security_opt:
    #   - no-new-privileges:true

networks:
  proxy:
    external: true