version: '3.7'
services:
  proxy:
    image: traefik:v2.11
    command: --providers.docker --api.insecure=true --entrypoints.web.address=:80
    ports:
      - 8080:8080
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  backend:
    build:
      context: ./backend
      target: final
    environment:
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_ADDRESS}:${DATABASE_PORT}/${DATABASE_NAME}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_REDIRECT_URL: ${GOOGLE_REDIRECT_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
      AWS_ENDPOINT: ${AWS_ENDPOINT}
      DEFAULT_DOMAIN: ${DEFAULT_DOMAIN}
      PUBLIC_BUCKET_URL: ${PUBLIC_BUCKET_URL}
    labels:
      traefik.http.routers.backend.rule: HostRegexp(`{subdomain:[a-zA-Z0-9.-]+}.localhost`) || PathPrefix(`/_api`)
      traefik.http.services.backend.loadbalancer.server.port: 8000
  client:
    build:
      context: ./dashboard
      target: final
    environment:
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_SERVER_URL: ${NEXT_SERVER_URL}
      NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
    labels:
      traefik.http.routers.client.rule: Host(`localhost`)
      traefik.http.services.client.loadbalancer.server.port: 3000