version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5433:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=simplyshare
      - POSTGRES_USER=simplyshare
      - POSTGRES_DB=simplyshare
      - POSTGRES_PORT=5432
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5051:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=
    depends_on:
      - postgres