version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5433:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=simplyshare
      - POSTGRES_USER=simplyshare
      - POSTGRES_DB=simplyshare
      - POSTGRES_PORT=5432